#!/bin/bash
# Sweep for: computer1/part2

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_1999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part2/config_2459.json --wandb True