#!/bin/bash
# Sweep for: computer1/part4

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_3999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part4/config_4099.json --wandb True