#!/bin/bash
# Sweep for: computer3/part4

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_11999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part4/config_12287.json --wandb True