#!/bin/bash
# Sweep for: computer2/part0

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part0/config_4919.json --wandb True