#!/bin/bash
# Sweep for: computer3/part2

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_10659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part2/config_9999.json --wandb True