#!/bin/bash
# Sweep for: computer2/part4

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_7999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part4/config_8199.json --wandb True