#!/bin/bash
# Sweep for: computer1/part1

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_0999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part1/config_1639.json --wandb True