#!/bin/bash
# Sweep for: computer3/part1

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part1/config_9839.json --wandb True