#!/bin/bash
# Sweep for: computer2/part1

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_4999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part1/config_5739.json --wandb True