#!/bin/bash
# Sweep for: computer1/part3

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_2999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer1/part3/config_3279.json --wandb True