#!/bin/bash
# Sweep for: computer2/part3

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_6999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part3/config_7379.json --wandb True