#!/bin/bash
# Sweep for: computer3/part3

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_10999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part3/config_11479.json --wandb True