#!/bin/bash
# Sweep for: computer3/part0

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8559.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8560.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8561.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8562.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8563.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8564.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8565.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8566.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8567.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8568.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8569.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8570.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8571.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8572.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8573.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8574.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8575.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8576.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8577.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8578.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8579.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8580.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8581.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8582.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8583.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8584.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8585.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8586.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8587.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8588.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8589.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8590.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8591.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8592.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8593.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8594.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8595.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8596.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8597.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8598.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8599.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8600.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8601.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8602.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8603.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8604.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8605.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8606.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8607.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8608.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8609.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8610.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8611.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8612.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8613.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8614.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8615.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8616.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8617.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8618.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8619.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8620.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8621.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8622.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8623.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8624.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8625.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8626.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8627.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8628.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8629.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8630.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8631.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8632.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8633.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8634.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8635.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8636.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8637.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8638.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8639.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8640.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8641.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8642.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8643.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8644.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8645.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8646.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8647.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8648.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8649.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8650.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8651.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8652.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8653.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8654.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8655.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8656.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8657.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8658.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8659.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8660.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8661.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8662.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8663.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8664.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8665.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8666.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8667.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8668.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8669.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8670.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8671.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8672.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8673.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8674.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8675.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8676.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8677.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8678.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8679.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8680.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8681.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8682.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8683.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8684.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8685.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8686.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8687.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8688.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8689.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8690.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8691.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8692.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8693.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8694.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8695.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8696.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8697.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8698.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8699.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8700.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8701.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8702.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8703.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8704.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8705.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8706.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8707.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8708.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8709.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8710.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8711.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8712.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8713.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8714.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8715.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8716.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8717.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8718.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8719.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8720.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8721.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8722.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8723.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8724.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8725.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8726.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8727.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8728.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8729.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8730.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8731.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8732.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8733.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8734.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8735.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8736.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8737.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8738.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8739.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_8999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer3/part0/config_9019.json --wandb True