#!/bin/bash
# Sweep for: computer2/part2

python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5740.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5741.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5742.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5743.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5744.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5745.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5746.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5747.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5748.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5749.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5750.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5751.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5752.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5753.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5754.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5755.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5756.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5757.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5758.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5759.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5760.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5761.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5762.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5763.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5764.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5765.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5766.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5767.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5768.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5769.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5770.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5771.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5772.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5773.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5774.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5775.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5776.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5777.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5778.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5779.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5780.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5781.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5782.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5783.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5784.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5785.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5786.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5787.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5788.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5789.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5790.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5791.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5792.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5793.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5794.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5795.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5796.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5797.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5798.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5799.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5800.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5801.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5802.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5803.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5804.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5805.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5806.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5807.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5808.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5809.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5810.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5811.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5812.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5813.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5814.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5815.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5816.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5817.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5818.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5819.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5820.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5821.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5822.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5823.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5824.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5825.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5826.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5827.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5828.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5829.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5830.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5831.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5832.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5833.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5834.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5835.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5836.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5837.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5838.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5839.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5840.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5841.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5842.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5843.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5844.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5845.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5846.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5847.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5848.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5849.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5850.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5851.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5852.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5853.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5854.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5855.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5856.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5857.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5858.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5859.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5860.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5861.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5862.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5863.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5864.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5865.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5866.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5867.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5868.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5869.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5870.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5871.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5872.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5873.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5874.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5875.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5876.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5877.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5878.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5879.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5880.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5881.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5882.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5883.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5884.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5885.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5886.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5887.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5888.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5889.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5890.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5891.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5892.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5893.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5894.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5895.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5896.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5897.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5898.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5899.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5900.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5901.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5902.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5903.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5904.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5905.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5906.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5907.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5908.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5909.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5910.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5911.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5912.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5913.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5914.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5915.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5916.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5917.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5918.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5919.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5920.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5921.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5922.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5923.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5924.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5925.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5926.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5927.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5928.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5929.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5930.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5931.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5932.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5933.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5934.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5935.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5936.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5937.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5938.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5939.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5940.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5941.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5942.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5943.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5944.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5945.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5946.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5947.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5948.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5949.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5950.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5951.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5952.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5953.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5954.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5955.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5956.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5957.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5958.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5959.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5960.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5961.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5962.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5963.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5964.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5965.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5966.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5967.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5968.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5969.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5970.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5971.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5972.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5973.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5974.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5975.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5976.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5977.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5978.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5979.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5980.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5981.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5982.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5983.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5984.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5985.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5986.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5987.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5988.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5989.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5990.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5991.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5992.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5993.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5994.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5995.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5996.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5997.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5998.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_5999.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6000.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6001.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6002.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6003.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6004.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6005.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6006.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6007.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6008.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6009.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6010.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6011.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6012.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6013.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6014.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6015.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6016.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6017.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6018.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6019.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6020.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6021.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6022.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6023.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6024.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6025.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6026.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6027.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6028.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6029.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6030.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6031.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6032.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6033.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6034.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6035.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6036.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6037.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6038.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6039.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6040.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6041.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6042.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6043.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6044.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6045.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6046.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6047.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6048.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6049.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6050.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6051.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6052.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6053.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6054.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6055.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6056.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6057.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6058.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6059.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6060.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6061.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6062.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6063.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6064.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6065.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6066.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6067.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6068.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6069.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6070.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6071.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6072.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6073.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6074.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6075.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6076.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6077.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6078.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6079.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6080.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6081.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6082.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6083.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6084.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6085.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6086.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6087.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6088.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6089.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6090.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6091.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6092.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6093.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6094.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6095.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6096.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6097.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6098.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6099.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6100.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6101.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6102.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6103.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6104.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6105.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6106.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6107.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6108.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6109.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6110.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6111.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6112.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6113.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6114.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6115.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6116.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6117.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6118.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6119.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6120.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6121.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6122.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6123.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6124.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6125.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6126.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6127.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6128.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6129.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6130.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6131.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6132.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6133.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6134.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6135.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6136.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6137.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6138.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6139.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6140.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6141.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6142.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6143.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6144.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6145.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6146.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6147.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6148.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6149.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6150.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6151.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6152.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6153.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6154.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6155.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6156.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6157.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6158.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6159.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6160.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6161.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6162.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6163.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6164.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6165.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6166.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6167.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6168.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6169.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6170.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6171.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6172.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6173.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6174.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6175.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6176.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6177.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6178.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6179.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6180.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6181.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6182.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6183.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6184.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6185.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6186.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6187.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6188.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6189.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6190.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6191.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6192.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6193.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6194.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6195.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6196.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6197.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6198.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6199.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6200.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6201.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6202.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6203.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6204.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6205.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6206.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6207.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6208.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6209.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6210.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6211.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6212.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6213.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6214.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6215.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6216.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6217.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6218.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6219.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6220.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6221.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6222.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6223.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6224.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6225.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6226.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6227.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6228.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6229.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6230.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6231.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6232.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6233.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6234.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6235.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6236.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6237.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6238.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6239.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6240.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6241.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6242.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6243.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6244.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6245.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6246.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6247.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6248.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6249.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6250.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6251.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6252.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6253.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6254.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6255.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6256.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6257.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6258.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6259.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6260.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6261.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6262.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6263.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6264.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6265.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6266.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6267.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6268.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6269.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6270.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6271.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6272.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6273.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6274.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6275.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6276.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6277.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6278.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6279.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6280.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6281.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6282.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6283.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6284.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6285.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6286.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6287.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6288.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6289.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6290.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6291.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6292.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6293.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6294.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6295.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6296.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6297.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6298.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6299.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6300.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6301.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6302.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6303.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6304.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6305.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6306.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6307.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6308.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6309.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6310.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6311.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6312.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6313.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6314.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6315.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6316.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6317.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6318.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6319.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6320.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6321.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6322.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6323.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6324.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6325.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6326.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6327.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6328.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6329.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6330.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6331.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6332.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6333.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6334.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6335.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6336.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6337.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6338.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6339.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6340.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6341.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6342.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6343.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6344.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6345.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6346.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6347.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6348.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6349.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6350.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6351.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6352.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6353.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6354.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6355.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6356.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6357.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6358.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6359.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6360.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6361.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6362.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6363.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6364.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6365.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6366.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6367.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6368.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6369.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6370.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6371.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6372.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6373.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6374.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6375.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6376.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6377.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6378.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6379.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6380.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6381.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6382.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6383.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6384.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6385.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6386.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6387.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6388.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6389.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6390.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6391.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6392.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6393.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6394.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6395.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6396.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6397.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6398.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6399.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6400.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6401.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6402.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6403.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6404.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6405.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6406.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6407.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6408.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6409.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6410.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6411.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6412.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6413.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6414.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6415.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6416.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6417.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6418.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6419.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6420.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6421.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6422.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6423.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6424.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6425.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6426.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6427.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6428.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6429.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6430.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6431.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6432.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6433.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6434.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6435.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6436.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6437.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6438.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6439.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6440.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6441.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6442.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6443.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6444.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6445.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6446.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6447.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6448.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6449.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6450.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6451.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6452.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6453.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6454.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6455.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6456.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6457.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6458.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6459.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6460.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6461.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6462.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6463.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6464.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6465.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6466.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6467.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6468.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6469.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6470.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6471.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6472.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6473.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6474.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6475.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6476.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6477.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6478.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6479.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6480.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6481.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6482.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6483.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6484.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6485.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6486.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6487.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6488.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6489.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6490.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6491.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6492.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6493.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6494.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6495.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6496.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6497.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6498.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6499.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6500.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6501.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6502.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6503.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6504.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6505.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6506.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6507.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6508.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6509.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6510.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6511.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6512.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6513.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6514.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6515.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6516.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6517.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6518.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6519.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6520.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6521.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6522.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6523.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6524.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6525.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6526.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6527.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6528.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6529.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6530.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6531.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6532.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6533.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6534.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6535.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6536.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6537.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6538.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6539.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6540.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6541.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6542.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6543.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6544.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6545.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6546.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6547.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6548.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6549.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6550.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6551.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6552.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6553.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6554.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6555.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6556.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6557.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6558.json --wandb True
python system/main.py --cfp ./hparams/sweep_STGM_grid_split/computer2/part2/config_6559.json --wandb True